name: Build LArContent

# Controls when the workflow will run
on:
  # Trigger the workflow on push to master, or any pull request.
  # workflow_dispatch allows manual running through the GitHub UI.
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

# Workflow with 1 stage: Build.
# Each of the sub-stages in the build job run in parallel.
jobs:
  build:

    # Use the latest ubuntu image: https://github.com/actions/runner-images
    runs-on: ubuntu-24.04
    name: LArContent - ${{ matrix.compiler.c }} - Monitoring ${{ matrix.monitoring }} - DL ${{ matrix.torch }}

    # Defines the build matrix, so what combinatorics of compiler etc. to test.
    strategy:
      fail-fast: false # Don't quit other jobs if one job fails.
      matrix:
        compiler: [ {cpp: g++-12, c: gcc-12}, {cpp: clang++, c: clang} ]
        monitoring: [ "ON", "OFF" ]
        torch: [ "ON", "OFF" ]

    # Set the compiler env vars to ensure the correct compiler is used.
    env:
        CC: ${{ matrix.compiler.c }}
        CXX: ${{ matrix.compiler.cpp }}

    steps:

      # First, checkout the repository...
      - name: Checkout LArContent
        uses: actions/checkout@v4

      # Install any missing system dependencies...
      - name: Setup Dependencies
        uses: ./.github/actions/setup-dependencies

      # Get Eigen...
      - name: Install Eigen
        uses: ./.github/actions/install-eigen
        with:
          version: '3.3.5'

      # Get ROOT, if needed...
      - name: Install ROOT
        uses: ./.github/actions/install-root
        with:
          monitoring: ${{ matrix.monitoring }}
          version: 'v6.28.12.Linux-ubuntu22-x86_64-gcc11.4'

      # Get Torch, if needed...
      - name: Install Torch
        uses: ./.github/actions/install-torch
        with:
          torch: ${{ matrix.torch }}
          version: '2.1.1'

      # Check all the required Pandora repos...
      - name: Get Pandora Repositories
        uses: ./.github/actions/checkout-repos
        with:
          monitoring: ${{ matrix.monitoring }}

      # Build all of Pandora...
      - name: Build Pandora
        uses: ./.github/actions/build-pandora

      # Check the PandoraInterface binary...
      - name: Test PandoraInterface
        uses: ./.github/actions/test-pandora

      # Finally, run the tests over some example data.
      - name: Run over MicroBooNE Open Data
        uses: ./.github/actions/run-opendata
        if: ${{ matrix.torch == 'ON' && matrix.monitoring == 'ON' }}
        with:
          torch: ${{ matrix.torch }}
          open_data_tar_url: 'https://cernbox.cern.ch/s/AdqqaF9T3lqetwc/download'